### ISSUE TITLE
Geometry tool running on latest Ubuntu LTS

### ISSUE THREAD

**Issue by mobernabeu** [hemelb-codes/hemelb#769] opened 2021-11-08 13:30 UTC
(At the moment this is 20.04, but the issue can be reopened when new versions come out.)

There's been good progress standardising the installation of the setup tool: https://github.com/hemelb-codes/hemelb/blob/main/geometry-tool/README.md

Test the instructions on the latest Ubuntu LTS, iron out issues, and compile details about how to deal with dependencies.

**Comment by mobernabeu** [comment] 2021-11-08 13:34
So far we've identified and issue with the standard GCC: https://github.com/hemelb-codes/hemelb/commit/180f88937fdfa33646d005b04d69e3fc5be9a7ec and another dependency not listed: `jq`

Try this `sudo apt-get install jq gcc-10 g++-10`

**Comment by rupertnash** [comment] 2021-11-08 13:50
Sorry - I've come to think of jq as a required tool for any environment these days

**Comment by rupertnash** [comment] 2021-11-08 14:39
The GCC bug is fixed in GGC 9.4. I suspect that the 8 series has had its last release now they're working on 12. This problem appears when CMake linking against CGAL adds the `-frounding-math` flag. We could try to catch this but I'm reluctant as it's a real compiler bug for a relatively old GCC.

I'll rebase the doc branch onto main. I suppose we could just apply it straight away and monotonically improve the docs?

**Comment by mobernabeu** [comment] 2021-11-09 06:44
Thanks, Rupert. I agree regarding not patching up for old compilers. We will document how to get the latest Ubuntu LTS onto the right GCC version.

I didn't realise what you were doing on the doc branch. Great stuff! Please do rebase and we will build on that.

**Comment by mobernabeu** [comment] 2021-11-15 12:39
We've made progress getting the setup tool installed in Ubuntu. Just to document how some of the dependencies where installed: 
```
conda install pybind11 boost skbuild boost pyyaml purest llvm=3.1
conda install -c condo-forge cgal
sudo apt-get libosmesa-dev
```
`llvm` and `Mesa` seemed to be need to ironing out issues with Python VTK.

@seede has had trouble compiling the tests and gets a segfault when trying to run the setuptool with a simple .stl. Ellie, could you please upload some screenshots to show the errors?

**Comment by seedel** [comment] 2021-11-15 15:05
This is the error I get when trying to open the setuptool:
![image (2)](https://user-images.githubusercontent.com/74921804/141804666-222dd2ff-7192-431b-b13f-98707c125e99.png)

**Comment by rupertnash** [comment] 2021-11-15 16:27
So the CI has a build recipe for ubuntu 20.04
https://github.com/hemelb-codes/hemelb/blob/main/.github/workflows/gmy-tool.yml
Don't know if that helps?

@seedel: for the segfault, how far does it get? Did the GUI start? Could you interact with it? Did the error occur when generating a GMY?

If the problem's on GUI start up, it will probably be a problem in how one (or more) of the dependencies are built. If it's during generation then it's most likely a bug in my code 😬

Can you try starting a python interpreter and importing the dependencies one at a time? E.g. wx, VTK, VMTK?

**Comment by mobernabeu** [comment] 2021-11-17 07:14
Thanks, Rupert.

I'm told that the setup tool segfaults before displaying starting the GUI and that the dependencies load fine on a Python interpreter.

I also understand that one of the setup tools unit tests is failing for @seedel and @Romain-Enjalbert, so we should start by looking at that. Could you guys confirm please and show us the error?

**Comment by rupertnash** [comment] 2021-11-17 07:52
Interactive debug today? Available 0930 until lunchtime

**Comment by Romain-Enjalbert** [comment] 2021-11-17 09:03
Hi, I'm free until 11h, but I am currently on Ubuntu 16 and am reluctant to upgrade on to 20 as I have the old setup tool running there for the moment in case I need it. The error is as follows. I tried importing the modules and they all import without error, and the segmentation fault occurs even before the GUI window opens.
```
romainenjalbert@romainenjalbert-HP-EliteBook-1050-G1:~/hemelb_main_test/hemelb/geometry-tool$ conda activate gmy-tool
(gmy-tool) romainenjalbert@romainenjalbert-HP-EliteBook-1050-G1:~/hemelb_main_test/hemelb/geometry-tool$ hlb-gmy-gui
Gtk-Message: 09:00:46.941: Failed to load module "overlay-scrollbar"
Gtk-Message: 09:00:46.943: Failed to load module "atk-bridge"
Gtk-Message: 09:00:46.943: Failed to load module "unity-gtk-module"
Gtk-Message: 09:00:46.948: Failed to load module "canberra-gtk-module"

(hlb-gmy-gui:4995): Gdk-WARNING **: 09:00:47.087: gdkdrawable-x11.c:952 drawable is not a pixmap or window

(hlb-gmy-gui:4995): Gdk-WARNING **: 09:00:47.088: gdkdrawable-x11.c:952 drawable is not a pixmap or window

(hlb-gmy-gui:4995): Gdk-WARNING **: 09:00:47.089: gdkdrawable-x11.c:952 drawable is not a pixmap or window
ERROR: In ../Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 797
vtkOSOpenGLRenderWindow (0x2921ce0): GL version 2.1 with the gpu_shader4 extension is not supported by your graphics driver but is required for the new OpenGL rendering backend. Please update your OpenGL driver. If you are using Mesa please make sure you have version 10.6.5 or later and make sure your driver in Mesa supports OpenGL 3.2.

ERROR: In ../IO/Geometry/vtkSTLReader.cxx, line 98
vtkSTLReader (0x25e95c0): A FileName must be specified.

ERROR: In ../Common/ExecutionModel/vtkExecutive.cxx, line 811
vtkCompositeDataPipeline (0x25e9df0): UpdateInformation invoked during another request.  Returning failure to algorithm vtkSTLReader(0x25e95c0).

ERROR: In ../Common/ExecutionModel/vtkExecutive.cxx, line 811
vtkCompositeDataPipeline (0x25e9df0): UpdateInformation invoked during another request.  Returning failure to algorithm vtkSTLReader(0x25e95c0).

ERROR: In ../Common/ExecutionModel/vtkExecutive.cxx, line 811
vtkCompositeDataPipeline (0x25e9df0): UpdateInformation invoked during another request.  Returning failure to algorithm vtkSTLReader(0x25e95c0).

ERROR: In ../Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x25e9df0): Algorithm vtkSTLReader(0x25e95c0) returned failure for request: vtkInformation (0x25ea890)
  Debug: Off
  Modified Time: 11291
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0
  FORWARD_DIRECTION: 0



Segmentation fault (core dumped)
```

**Comment by mobernabeu** [comment] 2021-11-17 10:48
Sorry guys, I'm back-to-back with meetings all morning, but please do go ahead without me. I suggest we start by looking at the failing unit tests and those are passing on the CI. It may give a hint at what's the issue with the dependencies.

**Comment by seedel** [comment] 2021-11-17 15:28
Hi Rupert, 
Thanks for your time this morning. We managed to install vmtk and vtk separately as discussed this morning, but we are having issues with `pip install .` afterwards. We are however unable to install `wxpython=4.0.6` as conda identifies package issues with the vtk from anaconda, although we don't know if that is the problem. The error is the following:
```
Processing /home/seede/hemelb_setup_tool/hemelb/geometry-tool
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy<1.20 in /home/seede/anaconda3/envs/gmy-tool-new/lib/python3.6/site-packages (from HlbGmyTool==1.2) (1.13.0)
Requirement already satisfied: vtk in /home/seede/anaconda3/envs/gmy-tool-new/lib/python3.6/site-packages (from HlbGmyTool==1.2) (8.1.0)
Requirement already satisfied: vmtk in /home/seede/anaconda3/envs/gmy-tool-new/lib/python3.6/site-packages (from HlbGmyTool==1.2) (1.4.0)
Collecting pyyaml
  Using cached PyYAML-6.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (603 kB)
Building wheels for collected packages: HlbGmyTool
  Building wheel for HlbGmyTool (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/seede/anaconda3/envs/gmy-tool-new/bin/python /home/seede/anaconda3/envs/gmy-tool-new/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpagfkclcj
       cwd: /tmp/pip-req-build-p6yky1k6
  Complete output (101 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 10.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 10.3.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-p6yky1k6/_cmake_test_compile/build
  -- The C compiler identification is GNU 10.3.0
  -- The CXX compiler identification is GNU 10.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
  -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: headers
  -- __cplusplus is 201402
  --   --> Do not link with Boost.Thread
  -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")
  -- Boost include dirs: /usr/include
  -- Boost libraries:
  '/home/seede/anaconda3/envs/gmy-tool-new/bin/python' '-c' 'import pybind11; print(pybind11.get_cmake_dir())'
  -- Found PythonInterp: /home/seede/anaconda3/envs/gmy-tool-new/bin/python (found version "3.6.1")
  -- Found PythonLibs: /home/seede/anaconda3/envs/gmy-tool-new/lib/libpython3.6m.so
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Found pybind11: /tmp/pip-build-env-olbxkpmg/overlay/lib/python3.6/site-packages/pybind11/include (found version "2.8.1" )
  -- Configuring done
  CMake Error at /tmp/pip-build-env-olbxkpmg/overlay/lib/python3.6/site-packages/pybind11/share/cmake/pybind11/pybind11Tools.cmake:165 (add_library):
    Cannot find source file:
  
      /tmp/Code/util/Vector3D.cc
  
    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
    .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
  Call Stack (most recent call first):
    CMakeLists.txt:98 (pybind11_add_module)
  
  
  CMake Error at /tmp/pip-build-env-olbxkpmg/overlay/lib/python3.6/site-packages/pybind11/share/cmake/pybind11/pybind11Tools.cmake:165 (add_library):
    No SOURCES given to target: Generation
  Call Stack (most recent call first):
    CMakeLists.txt:98 (pybind11_add_module)
  
  
  CMake Generate step failed.  Build files cannot be regenerated correctly.
    File "/tmp/pip-build-env-olbxkpmg/overlay/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 590, in setup
      languages=cmake_languages
    File "/tmp/pip-build-env-olbxkpmg/overlay/lib/python3.6/site-packages/skbuild/cmaker.py", line 248, in configure
      os.path.abspath(CMAKE_BUILD_DIR())))
  
  
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  
  Configuring Project
    Working directory:
      /tmp/pip-req-build-p6yky1k6/_skbuild/linux-x86_64-3.6/cmake-build
    Command:
      cmake /tmp/pip-req-build-p6yky1k6 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-p6yky1k6/_skbuild/linux-x86_64-3.6/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/seede/anaconda3/envs/gmy-tool-new/bin/python -DPYTHON_VERSION_STRING:STRING=3.6.1 -DPYTHON_INCLUDE_DIR:PATH=/home/seede/anaconda3/envs/gmy-tool-new/include/python3.6m -DPYTHON_LIBRARY:FILEPATH=/home/seede/anaconda3/envs/gmy-tool-new/lib/libpython3.6m.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-olbxkpmg/overlay/lib/python3.6/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
  
  Traceback (most recent call last):
  
  An error occurred while configuring with CMake.
    Command:
      cmake /tmp/pip-req-build-p6yky1k6 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-p6yky1k6/_skbuild/linux-x86_64-3.6/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/seede/anaconda3/envs/gmy-tool-new/bin/python -DPYTHON_VERSION_STRING:STRING=3.6.1 -DPYTHON_INCLUDE_DIR:PATH=/home/seede/anaconda3/envs/gmy-tool-new/include/python3.6m -DPYTHON_LIBRARY:FILEPATH=/home/seede/anaconda3/envs/gmy-tool-new/lib/libpython3.6m.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-olbxkpmg/overlay/lib/python3.6/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-req-build-p6yky1k6
    Working directory:
      /tmp/pip-req-build-p6yky1k6/_skbuild/linux-x86_64-3.6/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for HlbGmyTool
Failed to build HlbGmyTool
ERROR: Could not build wheels for HlbGmyTool which use PEP 517 and cannot be installed directly

```

**Closed** 2021-12-06 10:45 UTC

**Comment by seedel** [comment] 2022-02-03 10:50
I have tried this again and the `pip install .` in python-tools worked without error. 

Then

`python -m hlb.converters.GmyUnstructuredGridReader config.xml
`
gave the error:

'Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/seede/.local/lib/python3.8/site-packages/hlb/converters/GmyUnstructuredGridReader.py", line 18, in <module>
    from ..parsers.geometry.simple import ConfigLoader
  File "/home/seede/.local/lib/python3.8/site-packages/hlb/parsers/geometry/simple.py", line 14, in <module>
    from .generic import Domain, Block, AllSolidBlock, Site
  File "/home/seede/.local/lib/python3.8/site-packages/hlb/parsers/geometry/generic.py", line 11, in <module>
    from . import BaseSite
  File "hlb/parsers/geometry/BaseSite.pyx", line 1, in init hlb.parsers.geometry.BaseSite
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
'

**Comment by rupertnash** [comment] 2022-02-03 14:42
Hi @seedel -
Can you please open a new issue, since this is a new issue? (Unless the below lets you solve it)

It looks like your error is caused by building the gmy tool against one version of Numpy and then trying to use it with another. I recommend deleting the virtual env you're using and starting again with the instructions in the doc folder.
